# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '1.1.1.dev0+g4511cd5.d20230506'
__version_tuple__ = version_tuple = (1, 1, 1, 'dev0', 'g4511cd5.d20230506')
