on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - run: |
          docker build . --tag ghcr.io/atomicptr/hoyo-daily-logins-helper
          docker push ghcr.io/atomicptr/hoyo-daily-logins-helper