on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipx
          pipx install poetry
          poetry self add "poetry-dynamic-versioning[plugin]"
          poetry install
      - name: Lint
        run: poetry run ruff check hoyo_daily_logins_helper
      - name: Build
        run: |
          poetry build
          python -m pip install dist/hoyo_daily_logins_helper-*.whl --force-reinstall
          which hoyo-daily-logins-helper
